volumes:
  develop_postgres_data: {}
  develop_postgres_data_backups: {}
  develop_django_media: {}  


services:
  db:
    container_name: develop_postgres_db
    image: postgres:latest
    volumes:
      - develop_postgres_data:/var/lib/postgresql/data
      - develop_postgres_data_backups:/backups
    env_file:
      - ./project_management/.envs/.develop/.env
    ports:
      - 5432:5432

  
  django:
    build:
      context: .
      dockerfile: ./project_management/compose/develop/Dockerfile

    image: project_management_develop_django
    container_name: project_management_develop_django_container
    volumes:
      - develop_django_media:/app/project_management/media
      - ./project_management:/app
    depends_on:
      - db
    env_file:
      - ./project_management/.envs/.develop/.env
    ports:
      - 8000:8000
    