volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}  

  project_managment_production_redis_data: {}

services:
  db:
    container_name: production_postgres_db
    image: postgres:16
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./project_management/.envs/.production/.env
    ports:
      - 5432:5432

  
  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379


  django: &django
    build:
      context: .
      dockerfile: ./project_management/compose/production/Dockerfile
    image: project_management_production_django
    container_name: project_management_production_django_container
    volumes:
      - production_django_media:/app/project_management/media
    depends_on:
      - db
      - redis
    env_file:
      - ./project_management/.envs/.production/.env
    ports:
      - 8000:8000

  
  celeryworker:
    <<: *django
    image: project_managment_production_celeryworker
    container_name: project_managment_production_celeryworker
    depends_on:
      - db
      - redis
      - django
    ports: []
    command: /start-celery-worker


  celerybeat:
    <<: *django
    image: project_managment_production_celerybeat
    container_name: project_managment_production_celerybeat
    depends_on:
      - celeryworker
      - redis
      - db
      - django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: project_managment_production_flower
    container_name: project_managment_production_flower
    depends_on:
      - celeryworker
      - celerybeat
      - redis
      - django
    ports:
      - 5555:5555
    command: /start-flower
