volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}  


services:
  db:
    container_name: production_postgres_db
    image: postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./project_management/.envs/.production/.env
    ports:
      - 5432:5432

  
  django:
    build:
      context: .
      dockerfile: ./project_management/compose/production/Dockerfile

    image: project_management_production_django
    container_name: project_management_production_django_container
    volumes:
      - production_django_media:/app/project_management/media
    depends_on:
      - db
    env_file:
      - ./project_management/.envs/.production/.env
    ports:
      - 8000:8000
