volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}  

  project_managment_production_redis_data: {}

services:
  db:
    container_name: production_postgres_db
    image: postgres:16
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./project_management/.envs/.production/.env
    ports:
      - 5432:5432

  
  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379


  rabbitmq:
    container_name: rabbitmq_develop_container
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  django: &django
    build:
      context: .
      dockerfile: ./project_management/compose/production/Dockerfile
    image: project_management_production_django
    container_name: project_management_production_django_container
    volumes:
      - production_django_media:/app/project_management/media
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - ./project_management/.envs/.production/.env
    ports:
      - 8000:8000

  
  celeryworker:
    <<: *django
    image: project_managment_production_celeryworker
    container_name: project_managment_production_celeryworker
    depends_on:
      - db
      - redis
      - django
    ports: []
    command: /start-celery-worker


  celerybeat:
    <<: *django
    image: project_managment_production_celerybeat
    container_name: project_managment_production_celerybeat
    depends_on:
      - celeryworker
      - redis
      - db
      - django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: project_managment_production_flower
    container_name: project_managment_production_flower
    depends_on:
      - celeryworker
      - celerybeat
      - redis
      - django
    ports:
      - 8080:8080
    command: /start-flower

  send_email: &send_email
    build:
      context: .
      dockerfile: ./send_email/compose/develop/Dockerfile

    image: send_email_develop_django
    container_name: send_email_develop_django_container
    volumes:
      - ./send_email:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - ./send_email/.envs/.develop/.env
    ports:
      - 8002:8002
  
  send_email_celeryworker:
    <<: *send_email
    image: project_managment_develop_send_email_celeryworker
    container_name: project_managment_develop_send_email_celeryworker
    depends_on:
      - db
      - redis
      - send_email
      - rabbitmq
    ports: []
    command: /start-celery-worker


  consumer:
    <<: *send_email
    image: project_managment_develop_consumer
    container_name: project_managment_develop_consumer
    restart: always
    depends_on:
      - send_email_celeryworker
      - redis
      - db
      - send_email
      - rabbitmq
    ports: []
    command: /start-consumer

  send_email_flower:
    <<: *send_email
    image: project_managment_develop_send_email_flower
    container_name: project_managment_develop_send_email_flower
    depends_on:
      - send_email_celeryworker
      - redis
      - send_email
      - rabbitmq
    ports:
      - 8081:8081
    command: /start-flower