volumes:
  develop_postgres_data: {}
  develop_postgres_data_backups: {}
  develop_django_media: {}  

  project_managment_develop_redis_data: {}


services:
  db:
    container_name: develop_postgres_db
    image: postgres:16
    volumes:
      - develop_postgres_data:/var/lib/postgresql/data
      - develop_postgres_data_backups:/backups
    env_file:
      - ./project_management/.envs/.develop/.env
    ports:
      - 5432:5432


  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379


  rabbitmq:
    container_name: rabbitmq_develop_container
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672


  django: &django
    build:
      context: .
      dockerfile: ./project_management/compose/develop/Dockerfile

    image: project_management_develop_django
    container_name: project_management_develop_django_container
    volumes:
      - develop_django_media:/app/project_management/media
      - ./project_management:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - ./project_management/.envs/.develop/.env
    ports:
      - 8000:8000
    

  celeryworker:
    <<: *django
    image: project_managment_develop_celeryworker
    container_name: project_managment_develop_celeryworker
    depends_on:
      - db
      - redis
      - django
    ports: []
    command: /start-celery-worker


  celerybeat:
    <<: *django
    image: project_managment_develop_celerybeat
    container_name: project_managment_develop_celerybeat
    depends_on:
      - celeryworker
      - redis
      - db
      - django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: project_managment_develop_flower
    container_name: project_managment_develop_flower
    depends_on:
      - celeryworker
      - celerybeat
      - redis
      - django
    ports:
      - 8080:8080
    command: /start-flower


  send_email: &send_email
    build:
      context: .
      dockerfile: ./send_email/compose/develop/Dockerfile

    image: send_email_develop_django
    container_name: send_email_develop_django_container
    volumes:
      - ./send_email:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - ./send_email/.envs/.develop/.env
    ports:
      - 8002:8002
  
  send_email_celeryworker:
    <<: *send_email
    image: project_managment_develop_send_email_celeryworker
    container_name: project_managment_develop_send_email_celeryworker
    depends_on:
      - db
      - redis
      - send_email
      - rabbitmq
    ports: []
    command: /start-celery-worker


  consumer_task:
    <<: *send_email
    image: send_email_develop_consumer_task
    container_name: send_email_develop_consumer_task_container
    restart: always
    depends_on:
      - send_email_celeryworker
      - redis
      - db
      - send_email
      - rabbitmq
    ports: []
    command: /start-consumer-task

  consumer_summery:
    <<: *send_email
    image: send_email_develop_consumer_summery
    container_name: send_email_develop_consumer_summery_container
    restart: always
    depends_on:
      - send_email_celeryworker
      - redis
      - db
      - send_email
      - rabbitmq
    ports: []
    command: /start-consumer-summery

  send_email_flower:
    <<: *send_email
    image: project_managment_develop_send_email_flower
    container_name: project_managment_develop_send_email_flower
    depends_on:
      - send_email_celeryworker
      - redis
      - send_email
      - rabbitmq
    ports:
      - 8081:8081
    command: /start-flower